version: "3.8"

services:
  db:
    image: postgres:14
    container_name: tgbot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tgbot
      POSTGRES_USER: tgbot
      POSTGRES_PASSWORD: oomb
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    container_name: legacy-tgbot
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://tgbot:oomb@db:5432/tgbot

volumes:
  pgdata:
